version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    environment:
      MONGODB_URI: 'mongodb://sukhnagra:password123@sample-cluster.node.us-east-1.docdb.amazonaws.com:27017/payload-cms?tls=true&replicaSet=rs0&retryWrites=false'
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none

volumes:
  data:
  node_modules:
