name: Create release branch

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter tag"
permissions:
  contents: write        

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Verify release branch not exists
          run: |
            git fetch --all 
            if git branch -a | grep -q release-${{ github.event.inputs.name }}; then exit 1; else exit 0; fi
        - name: Create release branch
          run: git fetch --all --tags && git checkout -b release-${{ github.event.inputs.name }} ${{ github.event.inputs.name }} && git push --set-upstream origin release-${{ github.event.inputs.name }}